/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eprotea_icrengine_ICREngine */

#ifndef _Included_com_eprotea_icrengine_ICREngine
#define _Included_com_eprotea_icrengine_ICREngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eprotea_icrengine_ICREngine
 * Method:    loadModels
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_eprotea_icrengine_ICREngine_loadModels
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_eprotea_icrengine_ICREngine
 * Method:    predictCA
 * Signature: ([B[D)V
 */
JNIEXPORT void JNICALL Java_com_eprotea_icrengine_ICREngine_predictCA
  (JNIEnv *, jobject, jbyteArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
