/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eprotea_icrengine_ICREngine */

#ifndef _Included_com_eprotea_icrengine_ICREngine
#define _Included_com_eprotea_icrengine_ICREngine
#ifdef __cplusplus
extern "C" {
#endif
#undef com_eprotea_icrengine_ICREngine_CHEQUE_MY
#define com_eprotea_icrengine_ICREngine_CHEQUE_MY 0L
#undef com_eprotea_icrengine_ICREngine_CHEQUE_PH
#define com_eprotea_icrengine_ICREngine_CHEQUE_PH 1L
/*
 * Class:     com_eprotea_icrengine_ICREngine
 * Method:    loadModels
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_eprotea_icrengine_ICREngine_loadModels
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_eprotea_icrengine_ICREngine
 * Method:    predictCA
 * Signature: (I[B[D)V
 */
JNIEXPORT void JNICALL Java_com_eprotea_icrengine_ICREngine_predictCA
  (JNIEnv *, jobject, jint, jbyteArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
